version: '3.8'

services:
  app:
    build: ./app
    env_file:
      - ./app/.env
    networks:
      - service-network
    depends_on:

      - database
      - rabbitmq
    restart: unless-stopped

  ml_worker:
    build:
      context: .
      dockerfile: ml_worker/Dockerfile
    env_file:
      - ./ml_worker/.env
    networks:
      - service-network
    depends_on:
      - app
      - database
      - rabbitmq
    restart: unless-stopped

  web-proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web:/usr/share/nginx/html:ro
    networks:
      - service-network
    depends_on:
      - app
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - service-network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_running" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: on-failure

  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - service-network
    restart: on-failure

volumes:
  rabbitmq_data:
  postgres_data:


networks:
  service-network:
    name: service-network
    driver: bridge
